typedef unsigned int u32;
typedef signed int s32;
typedef unsigned char u8;
typedef signed char s8;
typedef unsigned short int u16;
#define CS0 (1<<7)
extern void delay_sec(unsigned int);
extern void delay_ms(unsigned int);
extern void lcd_cmd(unsigned char cmd);
extern void lcd_data(unsigned char data);
extern void lcd_string(char *ptr);
extern void lcd_init(void);
extern void lcd_cgram(void);
extern void lcd_integer(int );
extern void uart0_init(unsigned int);
extern void uart0_tx(unsigned char);
extern void uart0_string(unsigned char *);
extern unsigned char uart0_rx(void);
extern void adc_init(void);
extern u32 adc_read(s32);
extern void uart0_integer(int );
extern void uart0_float(float );
extern void lcd_float(float );
extern void config_vic(void);
extern void en_uart0_intr(void);
extern void spi0_init(void);
extern u8 spi0(u8 data);
extern u16 mcp3204_adc_read(u8 ch_num);
extern void uart0_rx_string(char  *ptr,int max_bytes);
extern void i2c_init(void);
extern void i2c_byte_write_frame(unsigned char sa,unsigned char mr,unsigned char data);
extern unsigned char i2c_byte_read_frame(u8 sa,u8 mr);
